/**
 * Context Capsule Types
 * Role-specific context injection at delegation time for the opencode-swarm plugin.
 * These types define the schema used by the Context Capsule feature to build
 * targeted, role-appropriate context packages for agent delegation.
 *
 * Capsules are generated by the capsule builder and consumed by delegated agents
 * to receive focused, relevant context without re-reading the entire codebase.
 *
 * See issue #1104, FR-003 and FR-004.
 */

/**
 * Reason a capsule was generated for a delegated agent.
 * Named `CapsuleDelegationReason` to avoid collision with `DelegationReason`
 * in `src/state.ts`, which serves a different purpose (tracking agent
 * interaction history).
 */
export type CapsuleDelegationReason =
	| 'new_task'
	| 'reviewer_rejection_fix'
	| 'critic_plan_review'
	| 'test_failure_fix';

/**
 * Agent roles that can receive context capsules.
 * Each role maps to a different capsule strategy determining
 * which context is included and how it is presented.
 */
export type AgentRole =
	| 'coder'
	| 'reviewer'
	| 'critic'
	| 'test_engineer'
	| 'sme';

/**
 * A single read policy instruction within a context capsule.
 * Tells the delegated agent whether it can trust the cached summary
 * for a given file or must read the original source directly.
 */
export interface ReadPolicyEntry {
	/** Relative file path this policy applies to */
	file_path: string;
	/** Whether the agent can trust the cached summary for this file */
	trust_summary: boolean;
	/** Whether the agent should read the actual file contents */
	read_original: boolean;
	/** Why this policy decision was made (e.g. "summary is stale", "file is small") */
	reason: string;
}

/**
 * Maps an agent role to its capsule construction strategy.
 * Controls how much context is included and which optional
 * sections (rejection history, coverage targets, claims) are added.
 */
export interface RoleProfile {
	/** The agent role this profile applies to */
	role: AgentRole;
	/** Strategy name (e.g. "scoped_files_plus_rejection") */
	strategy: string;
	/** Maximum number of files to include in the capsule */
	max_files: number;
	/** Whether to include prior rejection context for fix iterations */
	include_rejection: boolean;
	/** Whether to include coverage targets (relevant for test_engineer) */
	include_coverage: boolean;
	/** Whether to include claimed fix or implementation details */
	include_claims: boolean;
}

/**
 * Metadata returned by the capsule builder after generating a capsule.
 * Provides diagnostics on cache utilization, staleness detection,
 * and reading recommendations for the consuming agent.
 */
export interface CapsuleMetadata {
	/** Whether the capsule was generated successfully */
	success: boolean;
	/** File system path where the capsule was written */
	capsule_path: string;
	/** Estimated token count of the capsule content */
	token_estimate: number;
	/** Number of entries reused from the context map cache */
	cache_hits: number;
	/** Number of entries that required fresh computation */
	cache_misses: number;
	/** Number of stale entries detected during generation */
	stale_entries: number;
	/** Files the agent should still read directly despite summaries */
	recommended_reads: string[];
	/** Files whose cached summaries were sufficient (no direct read needed) */
	skipped_reads: string[];
}

/**
 * The full context capsule delivered to a delegated agent.
 * Contains all role-specific context needed for the agent to begin
 * work, including task goals, file scope, prior feedback, and
 * per-file read policies.
 */
export interface ContextCapsule {
	/** Task ID this capsule is for (e.g. "1.1", "2.3") */
	task_id: string;
	/** Which agent role receives this capsule */
	agent_role: AgentRole;
	/** Why this capsule was generated */
	delegation_reason: CapsuleDelegationReason;
	/** ISO 8601 timestamp of when the capsule was generated */
	generated_at: string;
	/** Files relevant to this task (the task's file scope) */
	files_in_scope: string[];
	/** What the task aims to accomplish */
	task_goal: string;
	/** Prior rejection reason, if this capsule is for a fix iteration */
	prior_rejection?: string;
	/** What needs to be fixed, if applicable */
	required_fix?: string;
	/** Repository facts relevant to this task */
	relevant_facts: string[];
	/** Review checklist items, included for reviewer capsules */
	review_checklist?: string[];
	/** Coverage targets, included for test_engineer capsules */
	coverage_targets?: string[];
	/** Per-file read policy: which summaries to trust vs which files to read */
	read_policy: ReadPolicyEntry[];
	/** The full markdown content of the capsule */
	content: string;
}
